### Title:
__Exact simulation and Almost exact simulation of the 3/2 model__

### Authors:
* Jan Baldeaux
* Choi J, Kwok YK
* Medvedev, A., Scaillet, O.

### Abstract:
* Baldeaux J (2012) Exact simulation of the 3/2 model. Int J Theor Appl Finan 15:1250032. https://doi.org/10.1142/S021902491250032X

This paper discusses the exact simulation of the stock price process underlying the 3/2 model. Using a result derived by Craddock and Lennox using Lie Symmetry Analysis, we adapt the Broadie-Kaya algorithm for the simulation of affine processes to the 3/2 model. We also discuss variance reduction techniques and find that conditional Monte Carlo techniques combined with quasi-Monte Carlo point sets result in significant variance reductions.

* Choi J, Kwok YK (2024) Simulation schemes for the Heston model with Poisson conditioning. European Journal of Operational Research 314(1):363–376. https://doi.org/10.1016/j.ejor.2023.10.048

Exact simulation schemes under the Heston stochastic volatility model (e.g., Broadie–Kaya and Glasserman–Kim) suffer from computationally expensive modified Bessel function evaluations. We propose a new exact simulation scheme without the modified Bessel function, based on the observation that the conditional integrated variance can be simplified when conditioned by the Poisson variate used for simulating the terminal variance. Our approach also enhances the low-bias and time discretization schemes, which are suitable for pricing derivatives with frequent monitoring. Extensive numerical tests reveal the good performance of the new simulation schemes in terms of accuracy, efficiency, and reliability when compared with existing methods.

* Medvedev, A., & Scaillet, O. (2007). Approximation and calibration of short-term implied volatilities under jump-diffusion stochastic volatility. The Review of Financial Studies, 20(2), 427-459.https://doi.org/10.1093/rfs/hhl013

We derive an asymptotic expansion formula for option implied volatility under a two factor jump-diffusion stochastic volatility model when time-to-maturity is small. We further propose a simple calibration procedure of an arbitrary parametric model to short-term near-the-money implied volatilities. An important advantage of our approximation is that it is free of the unobserved spot volatility. Therefore, the model can be calibrated on option data pooled across different calendar dates to extract information from the dynamics of the implied volatility smile. An example of calibration to a sample of S&P 500 option prices is provided. 


### References
* Baldeaux J (2012) Exact simulation of the 3/2 model. Int J Theor Appl Finan 15:1250032.
* Kouarfate IR, Kouritzin MA, MacKay A (2021) Explicit Solution Simulation Method for the 3/2 Model. In: Hernández‐Hernández D, Leonardi F, Mena RH, Pardo Millán JC (eds) Advances in Probability and Mathematical Statistics. Springer International Publishing, Cham, pp 123–145
* M. Jeanblanc, M. Yor and M. Chesney, Mathematical Methods for Financial Markets (Springer Finance, Springer, 2009).
* Choi J, Kwok YK (2024) Simulation schemes for the Heston model with Poisson conditioning. European Journal of Operational Research 314(1):363–376.
* Medvedev, A., & Scaillet, O. (2007). Approximation and calibration of short-term implied volatilities under jump-diffusion stochastic volatility. The Review of Financial Studies, 20(2), 427-459.

###  1. Assumption

According to Baldeaux(2013), The dynamics of the stock price under the 3/2 model under the risk-neutral measure are given by

$$
 \frac{dS_t}{S_t} = rdt + \sqrt{V_t}\rho dW_t^1 + \sqrt{V_t}\sqrt{1-\rho^2}dW_t^2 \tag{1}
$$

$$
 \frac{dV_t}{V_t} = \kappa (\theta - V_t)dt + \epsilon \sqrt{V_t}dW_t^1
$$

which is equivalent to

$$
 dV_t = \kappa V_t (\theta - V_t)dt + \epsilon V_t^{3/2}dW_t^1 \tag{2}
$$

where $W_t^1$ and $W_t^2$ are independent Brownian motions. Regarding the parameters, $r$ represents the constant interest rate, $\rho$ the instantaneous correlation between the return on the stock and the variance process and $\epsilon$ governs the volatility of volatility.The speed of mean reversion is given by $\kappa V_t$ and $\theta$ denotes the long-run mean of the variance process.

### 2.  Mathematical basis

Defining $X_t = \frac{1}{V_t}$, we obtain

$$
dX_t = (\kappa + \epsilon^2 - \kappa\theta X_t)dt - \epsilon \sqrt{X_t}dW_t^1 \tag{3}
$$
Hence, using the process $X_t$, we obtain the following dynamics for the stock price, where $u > t$

$$
S_u = S_t \exp\lbrace r(u-t) - 1/2 \int_t^u(X_s)^{-1}ds + \rho \int_t^u({\sqrt{X_s})^{-1}dW_s^1}\rbrace \exp \lbrace \sqrt{1-\rho^2} \int_t^u(\sqrt{X_s})^{-1} dW_s^2\rbrace \tag{4}
$$
From Baldeaux(2013), study $\log(X_t)$

$$
\int_t^u({\sqrt{X_s})^{-1}dW_s^1} = \frac{1}{\epsilon} (log(\frac{X_t}{X_u}) + (k + \frac{\epsilon^2}{2})\int_{t}^{u}\frac{ds}{X_s}-k\theta(u-t)) \tag{5}
$$

Therefore, the only thing we need to know is the distribution of $X_t$ and $\int_{t}^{u}\frac{ds}{X_s}$ conditional on $X_t$

### 3. Numerical method 
Using Broadie-Kaya algorithm, we specify the simulation as 3 steps

##### Step 1) Simulate $X_u|X_t$ using the noncentral $\chi^2$ distribution
$X_u$ is distributed as a noncentral $ \chi^2 $ distribution

$$
\frac{X_u{\rm exp}\lbrace \kappa \theta (u-t) \rbrace}{c(u-t)} \sim \chi^2(\delta, \alpha) \tag{6}
$$

where
$$
\delta = \frac{4(\kappa + \epsilon^2)}{\epsilon^2}, \quad \alpha = \frac{X_t}{c(u-t)}, \quad c(t) = \frac{\epsilon^2({\rm exp}\lbrace \kappa\theta u \rbrace - 1)}{4\kappa\theta}
$$

##### Step 2) $\int_t^u \frac{ds}{X_s}$ Given $X_u, X_t$
We first derive the characteristic function of $\int_u^t \frac{ds}{X_s}$, which is provided in Baldeaux(2013)

$$
E\left({\rm exp}\left\lbrace -a^* \int_0^t \frac{ds}{X_s} \ \bigg| \ X_t \right\rbrace \right) = \frac{I_{\sqrt{\nu^2+8a/\epsilon^2}}\left(-\frac{j\sqrt{X_tX_u}}{{\rm sinh}\left(j\Delta\right)}\right)}{I_{\nu}\left(-\frac{j\sqrt{X_tX_u}}{{\rm sinh}\left(j\Delta\right)}\right)}\tag{7}
$$

where $j=-\frac{2\kappa\theta}{\epsilon^2}$, $\Delta=\frac{u\epsilon^2}{4}-\frac{t\epsilon^2}{4}$, $v=\frac{n}{2}-1$.

##### Step 3) Exact method: Simulate $V_T$ with CDF by Laplace transform
Use Laplace transform to get the CDF of $\int_t^u \frac{ds}{X_s}$, then get the price.

##### Step 3) Almost exact method: Simulate $V_T$ with assumed distribution
Then we use the characteristic function to generate moment $M1$, $M2$. For simplicity, we assume that $\int_t^u \frac{ds}{X_s}$ follows the Inverse-Gaussian distribution / Gamma distribution / Log-normal distribution, then we can simulate $\int_t^u \frac{ds}{X_s}$.

##### Finally get the option price
$$
log(S_u) \sim N(log(S_t)+r(u-t)-\frac{1}{2}\int_t^u \frac{ds}{X_s}+\rho\int_t^u({\sqrt{X_s})^{-1}dW_s^1},  \sigma^2(t,u))\tag{8}
$$
where 
$$
\sigma^2(t, u) = (1-\rho^2)\int_t^u \frac{ds}{X_s}
$$
The option price is $C_{BS}(K,S_u, \sigma(t, u))$

In [62]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [63]:
import numpy as np
import time
import scipy.stats as spst
import scipy.special as spsp
import copy 
#import mp math as mp

import sys
sys.path.insert(sys.path.index('')+1, 'C:/Users/27261/Desktop/3_Courses in PHBS/3_09_AppliedStochasticProcess/Project_sv32_EMC')
import pyfeng as pf
import pyfeng.ex as pfex
np.set_printoptions(precision=4)

Run only one below

## Case I: Eq. (4.2) in Baldeaux (2012)

In [34]:
mr, theta, vov, rho, sigma, intr = 2.0, 1.5, 0.2, -0.5, 1.0, 0.05
strike, spot, texp = 1, 1, 1
p_exact = 0.443059

## Case II: Set 2 in Kouarfate et al. (2021)

In [35]:
sigma, mr, theta, vov, rho = 0.06, 22.84, 0.218, 8.56, -0.99
intr = 0

strike, spot, texp = np.array([95, 100, 105]), 100, 0.2
p_exact = np.array([10.364, 7.386, 4.938])
iv_exact = pf.Bsm(1).impvol(p_exact, strike, spot, texp)
iv_exact * 100

array([43.7918, 41.4578, 39.2219])

## Case III:in Kouarfate et al. (2021)

In [36]:
sigma, mr, theta, vov, rho = 0.06, 20.48, 0.218, 3.20, -0.99
intr = 0

strike, spot, texp = np.array([95, 100, 105]), 100, 0.5
p_exact = np.array([11.724, 8.999, 6.710])
iv_exact = pf.Bsm(1).impvol(p_exact, strike, spot, texp)
iv_exact * 100

array([32.8172, 31.9686, 31.1591])

## Pricing with Time Discreteization using Euler/Milstein scheme, Exact Stepping, Almost Exact Stepping

In [127]:
m = pfex.Sv32McTimeStep(sigma, vov, rho, mr, theta, intr)
m.set_num_params(n_path=1.6e5, dt=1/500, rn_seed=123456)
m.scheme = 1  # Euler/Milstein scheme, here dt should be small enough (dt=1/500)

m.correct_fwd = False

In [128]:
%%time
bias = m.price(strike, spot, texp) - p_exact
print(bias)

[-0.0548 -0.051  -0.0484]
CPU times: total: 1.39 s
Wall time: 1.39 s


In [239]:
m.set_num_params(n_path=1.6e5, dt=1/50, rn_seed=123456)
m.scheme = 2 # Exact Stepping with 1 / NCX2, here dt can be larger (dt=1/50)

In [252]:
%%time
bias = m.price(strike, spot, texp) - p_exact
print(bias)

[-0.0092 -0.0044  0.0014]
CPU times: total: 250 ms
Wall time: 246 ms


In [135]:
m.set_num_params(n_path=1.6e5, dt=1/50, rn_seed=123456)
m.scheme = 3 # Almost Exact Stepping with Poison-Gamma distribution, here dt can be even larger (dt=1/20)

In [136]:
%%time
bias = m.price(strike, spot, texp) - p_exact
print(bias)

[-0.0707 -0.0594 -0.0473]
CPU times: total: 391 ms
Wall time: 378 ms


## Pricing with Exact Simulation

In [208]:
m1 = pfex.Sv32McBaldeaux2012Exact(sigma, vov, rho, mr, theta, intr)
m1.set_num_params(n_path=10000, rn_seed=123456, dt=None)
m1.correct_fwd = False

In [211]:
%%time
bias = m1.price(strike, spot, texp) - p_exact
print(bias) # Sometimes the deviation can touch 0.26
# sometimes it will warn that RuntimeWarning: some failed to converge after 50 iterations warnings.warn(msg, RuntimeWarning)

[-0.0789 -0.0802 -0.0699]
CPU times: total: 1.22 s
Wall time: 1.25 s


## Pricing with IG approximation (Almost Exact Simulation)

In [212]:
m2 = pfex.Sv32McChoiKwok2023Ig(sigma, vov, rho, mr, theta, intr)
m2.set_num_params(n_path=100000, rn_seed=123456, dt=None)
m2.correct_fwd = False

In [234]:
%%time
bias = m2.price(strike, spot, texp) - p_exact
print(bias) # Sometimes the deviation can touch 0.13

[0.071  0.0779 0.0812]
CPU times: total: 250 ms
Wall time: 261 ms


# Pricing with FFT method

In [235]:
m3 = pf.sv_fft.Sv32Fft(sigma, vov, rho, mr, theta, intr)
m3.correct_fwd = False

In [238]:
%%time
bias = m3.price(strike, spot, texp) - p_exact
print(bias)

[-0.0005 -0.0012 -0.0009]
CPU times: total: 46.9 ms
Wall time: 43.7 ms
